In [1]:
import numpy as np
import pandas  as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [4]:
df=pd.read_csv("housing_price.csv")
display(df)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                  15         5612            1283   
1        -114.47     34.40                  19         7650            1901   
2        -114.56     33.69                  17          720             174   
3        -114.57     33.64                  14         1501             337   
4        -114.57     33.57                  20         1454             326   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                  52         2217             394   
16996    -124.27     40.69                  36         2349             528   
16997    -124.30     41.84                  17         2677             531   
16998    -124.30     41.80                  19         2672             552   
16999    -124.35     40.54                  52         1820             300   

       population  households  median_income  median_house_value  
0            1015         472         1.4936               66900  
1            1129         463         1.8200               80100  
2             333         117         1.6509               85700  
3             515         226         3.1917               73400  
4             624         262         1.9250               65500  
...           ...         ...            ...                 ...  
16995         907         369         2.3571              111400  
16996        1194         465         2.5179               79000  
16997        1244         456         3.0313              103600  
16998        1298         478         1.9797               85800  
16999         806         270         3.0147               94600  

[17000 rows x 9 columns]

In [3]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [5]:
x=df[["longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income"]].values
y=df["median_house_value"].values
x

array([[-114.31  ,   34.19  ,   15.    , ..., 1015.    ,  472.    ,
           1.4936],
       [-114.47  ,   34.4   ,   19.    , ..., 1129.    ,  463.    ,
           1.82  ],
       [-114.56  ,   33.69  ,   17.    , ...,  333.    ,  117.    ,
           1.6509],
       ...,
       [-124.3   ,   41.84  ,   17.    , ..., 1244.    ,  456.    ,
           3.0313],
       [-124.3   ,   41.8   ,   19.    , ..., 1298.    ,  478.    ,
           1.9797],
       [-124.35  ,   40.54  ,   52.    , ...,  806.    ,  270.    ,
           3.0147]])

In [6]:
y

array([ 66900,  80100,  85700, ..., 103600,  85800,  94600], dtype=int64)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=0)


In [15]:
print("shape of x",(x_train).shape,(x_test).shape)

shape of x (13600, 8) (3400, 8)


In [16]:
print("shape of y",(y_train).shape,(y_test).shape)

shape of y (13600,) (3400,)


In [19]:
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [20]:
reg.score(x_test,y_test)

0.6321014171579442

In [21]:
reg.coef_

array([-4.33863939e+04, -4.31113378e+04,  1.15576940e+03, -9.28217711e+00,
        1.23826022e+02, -3.71486621e+01,  4.07777661e+01,  4.05767360e+04])

In [22]:
reg.intercept_

-3644153.7773250677

In [23]:
y_pred=reg.predict(x_test)
y_pred

array([211157.0633542 , 218581.6429858 , 465317.31295568, ...,
       201751.23969636, 160873.51846962, 138847.26913354])

In [26]:
import statsmodels.api as sm
X2 = sm.add_constant(x)
est = sm.OLS(y, X2)
est2 = est.fit()
print(est2.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.641
Model:                            OLS   Adj. R-squared:                  0.641
Method:                 Least Squares   F-statistic:                     3798.
Date:                Mon, 31 Jul 2023   Prob (F-statistic):               0.00
Time:                        14:41:13   Log-Likelihood:            -2.1365e+05
No. Observations:               17000   AIC:                         4.273e+05
Df Residuals:                   16991   BIC:                         4.274e+05
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.621e+06   6.92e+04    -52.312      0.0