In [3]:
import numpy as np
d=[[0,1,2],[3,4,5],[6,7,8]]#2 dim
x=np.array(d)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
import numpy as np

In [5]:
x.shape

(3, 3)

In [6]:
x.dtype

dtype('int32')

In [7]:
x.size

9

In [8]:
x.itemsize

4

In [9]:
x.ndim

2

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
p=np.arange(0,20,5)#single dim
print(p)

[ 0  5 10 15]


In [12]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [13]:
import numpy as np
f=np.array([1,2,3,7,986,8])
l=f.copy()
print(l)

[  1   2   3   7 986   8]


In [14]:
#arithematic operation
n=np.arange(4)
print(n)
m=np.arange(4,8)
print(m)
print(n+m)

[0 1 2 3]
[4 5 6 7]
[ 4  6  8 10]


In [15]:
print(n*m)

[ 0  5 12 21]


In [16]:
#2 dim
l=np.ones((3,3))
print(l)
o=np.arange(0,9).reshape(3,3)
print(o)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
print(l*o)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [18]:
print(np.dot(o,l))

[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [19]:
q=np.arange(0,16).reshape(2,8)
print(q)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [20]:
w=np.arange(0,9).reshape(3,3)
print(w)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
w[[1,0]]=w[[0,1]]#swap first two rows
print(w)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [22]:
e=np.random.randint(0,100,5)
r=np.random.randint(0,100,5)
print(e,r)

[67  4 52 87 28] [62 14 11 85 99]


In [23]:
np.equal(e,r)

array([False, False, False, False, False])

In [24]:
np.greater(e,r)

array([ True, False,  True,  True, False])

In [25]:
np.less(e,r)

array([False,  True, False, False,  True])

In [26]:
np.isreal(e)

array([ True,  True,  True,  True,  True])

In [27]:
np.iscomplex(r)

array([False, False, False, False, False])

In [28]:
np.sqrt(e)#universal fun

array([8.18535277, 2.        , 7.21110255, 9.32737905, 5.29150262])

In [29]:
b=6
h=4
y=np.hypot(b,h)
print(y)

7.211102550927978


In [30]:
np.isnan(b)

False

In [31]:
g=[np.log(-1)]
p=np.isnan(g)
print(p)

[ True]


C:\Users\admin\AppData\Local\Temp\ipykernel_6920\3510995662.py:1: RuntimeWarning: invalid value encountered in log
  g=[np.log(-1)]


In [32]:
h=np.array([1,2,3,4,5])
j=np.array([6,7,8,4,10])
k=np.logical_and(h,j)
print(k)

[ True  True  True  True  True]


In [33]:
t=np.logical_or(h,j)
print(t)

[ True  True  True  True  True]


In [34]:
u=np.logical_xor(h,j)
print(u)

[False False False False False]


In [35]:
i=np.logical_not(h,j)
print(i)

[0 0 0 0 0]


In [36]:
arr=np.arange(20,26)
v=arr[0]
print(v)

20


In [37]:
arr[4]#indexing

24

In [38]:
arr[1:5]#slicing

array([21, 22, 23, 24])

In [39]:
c=np.arange(0,20)
z=slice(1,19,2)
print(c[z])

[ 1  3  5  7  9 11 13 15 17]


In [40]:
import numpy as np
q=np.arange(9).reshape(3,3)
print(q)
for s in np.nditer(q):
      print(s)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
1
2
3
4
5
6
7
8


In [41]:
q.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [42]:
q.ravel()#also reshape(-1) help to convert 2to1 dim a.flatten()is also use

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
a=np.array([12,24,35,46,58,69,70,88,93,40])#Fancy indexing
ind=np.array([[1,4],[5,7]])
print(a[ind])



[[24 58]
 [69 88]]


In [44]:
ex=[]
for i in range(5): 
    n=int(input('value:'))
    ex.append(n)  
    print(ex)

value:


ValueError: invalid literal for int() with base 10: ''

In [45]:
e=np.array([[1,2],[5,7]])
p=np.array([[8,9],[5,4]])
l=np.concatenate((e,p),axis=0)
print(l)

[[1 2]
 [5 7]
 [8 9]
 [5 4]]


In [46]:
k=np.hstack((e,p))
print(k)

[[1 2 8 9]
 [5 7 5 4]]


In [47]:
o=np.vstack((e,p))
print(o)

[[1 2]
 [5 7]
 [8 9]
 [5 4]]


In [48]:
np.hsplit(l,2)

[array([[1],
        [5],
        [8],
        [5]]),
 array([[2],
        [7],
        [9],
        [4]])]

In [49]:
np.vsplit(l,2)

[array([[1, 2],
        [5, 7]]),
 array([[8, 9],
        [5, 4]])]